Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"
  config.vm.network :forwarded_port, guest: 27017, host: 27017

  config.vm.provider "virtualbox" do |v|
    v.name = "twitter-export-mongodb"
  end

  config.vm.provision :shell, path: "scripts/post_install.sh"
end
